xos: 
  - osx
language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode11.3
      compiler: clang
      env:
        - Qt5_DIR="/usr/local/opt/qt" 
        - PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"
        - CPPFLAGS="-I/usr/local/opt/llvm/include"
        - LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

addons:
  homebrew:
    packages: 
      - qt5
      - eigen
      - opencv
      - cmake
      - tree
    update: true

script:
  # Temporal untill merged
  - rm -r video-ps3eye/ps3eye-driver
  - git clone https://github.com/rvt/PS3EYEDriver video-ps3eye/ps3eye-driver
  - cd video-ps3eye/ps3eye-driver && git checkout osx-build-fix
  # Temporal untill merged
  - travis/build-opentrackdepends.sh
  - travis/generate-travis-cmake.sh
  - pwd
  - which cmake
  - cmake --version 
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1 install
  - cd build/install/opentrack.app
  - tree
