xos: 
  - osx
language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode11.3
      compiler: clang
      env:
        - LDFLAGS="-L/usr/local/opt/qt/lib"
        - CPPFLAGS="-I/usr/local/opt/qt/include"
        - Qt5_DIR="/usr/local/opt/qt" 
        - PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"
        #- CPPFLAGS="-I/usr/local/opt/llvm/include"
        #- LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

addons:
  homebrew:
    packages: 
      - qt5
      - eigen
      - opencv
      - cmake
      - tree
    update: true

script:
  - travis/build-opentrackdepends.sh
  - travis/generate-travis-cmake.sh
  - tree
  - which cmake
  - cmake --version 
  - mkdir build
  - cd build
  - cmake ..
  - make -j 6 install
