os: 
  - osx
language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode11.3
      env:
        - LDFLAGS="-L/usr/local/opt/qt/lib"
        - CPPFLAGS="-I/usr/local/opt/qt/include"
        - Qt5_DIR="/usr/local/opt/qt" 
        - PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig"

addons:
  homebrew:
    packages: 
      - qt5
      - eigen
      - opencv
      - cmake
    update: true

before_script:
  - travis/build-opentrackdepends.sh

script:
  - tree
  - which cmake
  - cmake --version 
  - mkdir build
  - cd build
  - cmake ..
  - make -j 6 install
